# Generated by Django 4.1.7 on 2023-03-26 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_actor_age_actor_birthday_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата Рождения'),
        ),
    ]
