# Generated by Django 4.1.7 on 2023-03-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_reviews_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='author_name',
        ),
    ]
